### PR TITLE
Include event location upon creation

### PR DESCRIPTION
**Pull request by lxieyang**

### CODE REVIEW

**Comment by DieterKoblenz** [comment]
It's great, use this to make my google home a bit more useful.
The problem with @lxieyang version is in the multiday events when it adds the same event every day of the multiday.

**Comment by Laghzz** [comment]
Really love the script, thanks guys!

I am quite new to this and was wondering if the original script by @DieterKoblenz has to be run manually every day in order to process new events. 

Also, @lxieyang when using your script, it keeps coming back with -- TypeError: Cannot call method "getEventForDay" of null. (line 69, file "Code") -- I have tried to play around with it with my very limited knowledge, but I just cannot figure it out. It would be great if you could help! This would make my Google Home Mini much more useful.

**Comment by DieterKoblenz** [comment]
It is definately not my script but you should be able to run in daily.

**Comment by lxieyang** [comment]
@Laghzz Thanks for spotting the bug! I wrapped the whole main logic in a try/catch block so hopefully, the issues will be resolved.

**Pull request closed without merging**
